
spring:
  profiles:
    active: prod
  application:
    name: Chat
  # mysql connection
  datasource:
    url: jdbc:mysql://localhost:3306/chatting?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: chatting
    password: Chatting@123
    druid:
      initial-size: 10
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: "SELECT 'x'"
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,slf4j,wall
      filter:
        stat:
          db-type: h2
          log-slow-sql: true
          slow-sql-millis: 2000
        wall:
          db-type: h2
          enabled: true
        slf4j:
          enabled: true
      time-between-log-stats-millis: 3600000
  #session config
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: club.lzlbog.chatting:session
  # redis connection
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
  # 开发测试自动重启
  devtools:
    restart:
      enabled: true
      exclude: static/**
    livereload:
      enabled: true
  #Http
  http:
    #字符编码
    encoding:
      charset: UTF-8
      # 将request和response的字符编码均设置成utf-8
      force: true
  # java mail配置 必须与发送邮件代码中的from一致
  mail:
    host: smtp.aliyun.com
    #port: 25
    username: args1
    password: args2
    properties: {mail.smtp.connectiontimeout: 5000, mail.smtp.timeout: 3000, mail.smtp.writetimeout: 5000, mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory, mail.smtp.socketFactory.port: 465, mail.smtp.port: 465}
    port: 465
  # 模板引擎
  thymeleaf:
    mode: html
    cache: true
  mvc:
    static-path-pattern: /static/**
  # 上传文件的最大值
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 错误日志输出到文件
logging:
  file: ./logs/chatting.log

# Mybatis Plus
mybatis-plus:
  # mapper.xml文件
  mapper-locations: classpath:mapper/*Mapper.xml
  #实体类扫描
  type-aliases-package: club.lzlbog.chatting.entity
  global-config:
    #主键类型
    id-type: 3
    # 字段策略
    field-strategy: 2
    #驼峰转下划线
    db-column-underline: true
    # 表前缀
    table-prefix: 'tbl_'
    # 调试器 刷新mapper
    refresh-mapper: true
    #数据库大写转下划线
    capital-mode: true
    # 逻辑删除
    logic-delete-value: -1
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
#    meta-object-handler: com.li.blog.config.handler.CustomMetaObjectHandler
  configuration:
    #配置返回数据库，自动匹配无序as
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: null
    # 一级缓存：SqlSession范围
    #local-cache-scope: session



#  boot:
#    admin:
#      client:
#        url: http://149.129.115.52:8088
#        username: li
#        password: long@123
#        instance:
#          service-url: http://chat.lzlbog.club/
#        enabled: false

# 监控
#management:
#  endpoint:
#    shutdown:
#      enabled: false
#    beans:
#      cache:
#        time-to-live: 10s
#    health:
#      show-details: always
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#        exclude: "configprops"
#info:
#  app:
#    name: @project.name@
#    description: @project.description@
#    version: @project.version@
#    groupId: @project.groupId@
#    artifactId: @project.artifactId@

